#!/bin/bash

#Se crea la funcion que utiliza mkdir para crear tanto el directorio padre como los directorios hijos.
mkpt() {
        mkdir -p "$1"/{nmap,scripts,loot}
}

# Llama a la función con el directorio principal como argumento.
mkpt "$1"
